services:
  backend-dev:
    image: ghcr.io/nstafford/pocus-health-backend:dev
    restart: unless-stopped
    container_name: pocus-backend-dev
    environment:
      - PORT=8001
    ports:
      - "127.0.0.1:8001:8000"
